### ISSUE TITLE
Programming issue

### ISSUE THREAD

**Issue by itay-grudev** [Xinyuan-LilyGO/T-TWR#6]
I have two T-TWR, rev 1 and I can't program any of them.

I followed your reset procedure in the troubleshooting section, but when I do that the serial device disappears from the USB Device list.

Do you have any other advice?

**Comment by lyusupov** [comment]
> **T-TWR, rev 1** , I can't program any of them.

- https://t-twr.readthedocs.io/en/latest/troubleshooting.html#sa868-power-problem
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/#upload-application-for-debugging

**Comment by itay-grudev** [comment]
@lewisxhe As I said, when I follow that procedure the device disappears from the USB. It's very strange and I can't upload anything.

**Comment by SensorsIot** [comment]
My two boards also create lots of problems. If I follow your advice and reset it with GPIO0 pressed, the board draws 1.7A, and the SA868 gets extremely hot (but no output power on RF). I managed to program one board using RX/TX pins. The other one only creates brownouts (also with a battery attached).

**Comment by lyusupov** [comment]
Version **1**.x of T-TWR uses GPIO39 to drive H/L pin of SA868 module.
Unfortunately, it is not well documented by Espressif that GPIO39 has hardware  pull up after reset to meet some JTAG MTCK purpose requirements.

https://www.esp32.com/viewtopic.php?f=12&p=111105

This _(not well documented)_ pull-up state can cause an excessive heat of SA868 module until it is explicitly set to LOW by a customer's firmware. 
**LilyGO factory firmware pulls the GPIO39 down at very first steps of it's initialization sequence**.

OpenOCD firmware uploading method is knowing good to operate with T-TWR 1.3:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/jtag-debugging/#upload-application-for-debugging

**This issue is not applicable for version 2.x** of the T-TWR which is also known as **T-TWR Plus**.

Here is an example of the **T-TWR Plus** operating as [**APRS Beacon**](https://en.wikipedia.org/wiki/Automatic_Packet_Reporting_System) device.
https://drive.google.com/file/d/18a2PpIE4KQ6lYPcmPZgXnCYFSRYEqKz-/view

A bit more info about this particular use case is available there: https://github.com/lyusupov/SoftRF/wiki/Ham-Edition

**Comment by SensorsIot** [comment]
I think that these boards are not fit for purpose and I will throw my 4 pcs into the waste. If you sell such a product with Arduino software it should be programmable with Arduino SW.
The problem with the high current starts when you set the board into the upload status (press boot + reset), which is needed in many cases for programming. I do not exactly know why. Most probably not only because of GPIO39. H/L has no function in the RX mode of the SA868 module.
For all that that want to use them anyway: Use RX/TX for programming instead of USB. Reset the board and wait till the Arduino IDE starts to upload. Then press boot and quickly reset. Now it uploads, and the module warms up. Immediately after upload, reset the board, and if you set PTT and H/L to low, as written above, the board is not boiling. If you set the Arduino parameters correctly, it might even be possible to program it with USB from now on.

**Comment by lyusupov** [comment]
> I think that these boards are not fit for purpose 

It was reported by LulyGO that the engineer who designed T-TWR **1.3** no longer works for that company. Some online stores may still sell stocks of v1.3 boards remaining...

**T-TWR Plus**  (a.k.a. v2.0) is supported by Adafruit **TinyUF2** bootloader since 0.16.0:
https://github.com/adafruit/tinyuf2/releases/tag/0.16.0
Read this PR for details: https://github.com/adafruit/tinyuf2/pull/337

**![](https://user-images.githubusercontent.com/5849637/256504607-6a3edc29-3a94-49f3-a623-65f0ad6695ec.png)**

Installing a new firmware into T-TWR Plus with pre-installed TinyUF2 is as simple as mouse "drag and drop" in a File Manager.
https://github.com/lyusupov/SoftRF/blob/master/software/firmware/binaries/README.md#esp32-s3

**Comment by SensorsIot** [comment]
Unfortunately, this is not entirely true. Just checked and the official Lilygo Store still sells the old version.

**Comment by SensorsIot** [comment]
BTW: I just saw your name on my new T-Echo. If you are responsible for it: Congratulations! It should appear in one of my next videos

**Comment by lyusupov** [comment]
**T-Echo** is a result of collaboration of **LilyGO** with 
- [SoftRF project](https://github.com/lyusupov/SoftRF) and
- [Meshtastic project](https://meshtastic.org/) , https://meshtastic.discourse.group/t/exciting-new-ttgo-board-prototype/1399/50

**Lewis** is the LilyGO leading engineer who were driving force for development of the T-Echo in 2020 / 2021.

https://github.com/Xinyuan-LilyGO/T-TWR/issues/6#issuecomment-1653663379

<img width="533" alt="image" src="https://github.com/Xinyuan-LilyGO/T-TWR/assets/5849637/0e125148-e0e1-4b7e-87ef-4171bdcb8b18">


**Lewis** is driving development of T-TWR **V2.x** (a.k.a. Plus) series at this time.

**Comment by lewisxhe** [comment]
Hi @SensorsIot ,

If you encounter problems during use, please contact customer service for processing.

**Comment by iontodirel** [comment]
does not work for me, and now it's bricked with a blank screen 👎 any idea of alternate ways to flash it?
